//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KabiLottery2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserId
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Myname { get; set; }
        public string Comment { get; set; }
        public Nullable<System.DateTime> Datetime { get; set; }
        public Nullable<bool> LotteryName { get; set; }
        public Nullable<bool> LotteryMyName { get; set; }
        public Nullable<bool> LotteryComment { get; set; }
        public Nullable<int> Chance { get; set; }
    }
}
